PharosLoginPortalDK/PharosLoginPortal.Web/Controllers/NewLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PharosLoginPortal.Repository.Database;
using PharosLoginPortal.Repository.Models;

namespace PharosLoginPortal.Web.Controllers
{

    [Authorize]
    public class NewLoginController : Controller
    {
        private readonly RegisterRepository _registerRepository;
        private readonly UnitOrganisationRepository _unitOrganisationRepository;
        private readonly UserRepository _userRepository;
        
        public NewLoginController()
        {
            _registerRepository = new RegisterRepository();
            _unitOrganisationRepository = new UnitOrganisationRepository();
            _userRepository = new UserRepository();
        }
      
        public ActionResult Index()
        {
            var myViewModel = new UserNewLoginIndexViewModel();
            var registers = _registerRepository.GetAllRegisters();

            myViewModel.Registers.AddRange(registers);
            return View(myViewModel);
        }
      
        public JsonResult GetOrganisationAndUnits(int id)
        {
            var result = _unitOrganisationRepository.GetOrganisationAndUnits(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetOrganisationAndUnitsCountyList(int id)
        {
            var result = _unitOrganisationRepository.GetOrganisationAndUnitsCountyList(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    
        public JsonResult GetOrganisationsAndUnitsCommunityList(int id, int countyId)
        {
            var result = _unitOrganisationRepository.GetOrganisationsAndUnitsCommunityList(id, countyId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
     
        public JsonResult GetOrganisationAndUnitsOnCountyAndCommunity(int id, int countyId, int communityId)
        {
            var result = _unitOrganisationRepository.GetOrganisationAndUnitsOnCountyAndCommunity(id, countyId, communityId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    
        public JsonResult DoesPersonalLoginExist(int? unitId, string password, string username, int registerId)
        {
            var logging = new LoggingRepository();
            logging.LoggToDatabase(1, 22, 0, "Submited password and username for personal login");
            var userRepository = new UserRepository();
            var result = userRepository.DoesPersonalLoginExist(unitId, password, username, registerId); 

            return Json(result, JsonRequestBehavior.AllowGet);
        }
   
        public JsonResult CreateSithsLoginRequest(string email, string userComment, int? userId, int registerId, int? organisationId, int? unitId, int loginRequestId)
        {
            var hsaIdentity = User.GetAuthifyUser().hsa_id;
            var firstName = User.GetAuthifyUser().firstname;
            var lastName = User.GetAuthifyUser().lastname;
            var trainingId = User.GetAuthifyUser().trainingId;

            if (userId <= 0)
            {
                userId = null;
            }

            if (organisationId <= 0)
            {
                organisationId = null;
            }

            if (unitId < 0) //unitId can be 0 and still be valid
            {
                unitId = null;
            }

            var logging = new LoggingRepository();
            logging.LoggToDatabase(1, 23, 0, "Submited New Login Request");

            var sithsLoginExist = _userRepository.DoesSithsLoginExist(registerId, hsaIdentity, organisationId, unitId);
            if (sithsLoginExist == 1)
            {
                logging.LoggToDatabase(2, 24, 0, "Siths login exists");

                return Json("Siths login finns redan", JsonRequestBehavior.AllowGet);
            }

            var loginRequestExist = _userRepository.DoesPendingSithsLoginRequestExist(registerId, hsaIdentity,
                organisationId, unitId);
            if (loginRequestExist == 1)
            {
                logging.LoggToDatabase(2, 25, 0, "Request exists");
                return Json("Ansökan finns redan", JsonRequestBehavior.AllowGet);
            }

            logging.LoggToDatabase(1, 26, 0, "Request submited to database");
            var result = _userRepository.CreateSithsLoginRequest(hsaIdentity, firstName, lastName, email, userComment, userId, registerId, organisationId, unitId, trainingId, loginRequestId);

            if (result.HasValue)
            {
                //Send email notifications
                var register = _registerRepository.GetRegister(registerId);
                var unitName = "N/A";
                if (unitId.HasValue)
                {
                    var unit = _unitOrganisationRepository.GetUnit(unitId.Value, registerId);
                    if (unit != null)
                        unitName = unit.Name;
                }

                var senderAddress = !string.IsNullOrWhiteSpace(register.SenderEmailAddress)
                    ? register.SenderEmailAddress
                    : !string.IsNullOrWhiteSpace(register.AdminEmailAddress1) 
                        ? register.AdminEmailAddress1 
                        : register.AdminEmailAddress2;

                var adminEmailAddresses = "";
                adminEmailAddresses += register.AdminEmailAddress1 ?? "";
                adminEmailAddresses += (adminEmailAddresses != "" ? "," : "") + register.AdminEmailAddress2;

                //To the user
                EmailUserConfirmation(hsaIdentity, "New SITHS Login Request created", "Din förfrågan har skickats", senderAddress, email, firstName, register.RegisterName, unitName);

                //To the administrator
                EmailAdminConfirmation(hsaIdentity, "New SITHS Login Request created", "[" + register.RegisterName + "] En ny inloggningsförfrågan har skickats in", senderAddress, adminEmailAddresses, lastName + ", " + firstName, register.RegisterName, unitName);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public void EmailUserConfirmation(string hsaIdentity, string description, string emailSubject, string senderAddress, string addressees, string name, string registerName, string unitName)
        {
            var emailBody = FormatEmailBody(hsaIdentity, name, registerName, unitName, "~/MailTemplates/UserMail.txt");
            const string senderName = "Pharos Login Portal";
            const string attachmentName = "";

            var service = new Npat.Eyenet.EmailService.IwsZooshMSservice();

            service.SendEmail(emailSubject, emailSubject, emailBody, senderName, senderAddress, addressees, attachmentName, null);
        }

        public void EmailAdminConfirmation(string hsaIdentity, string description, string emailSubject, string senderAddress, string addressees, string name, string registerName, string unitName)
        {
            var emailBody = FormatEmailBody(hsaIdentity, name, registerName, unitName, "~/MailTemplates/AdminMail.txt");
            const string senderName = "Pharos Login Portal";
            const string attachmentName = "";

            var service = new Npat.Eyenet.EmailService.IwsZooshMSservice();

            service.SendEmail(emailSubject, emailSubject, emailBody, senderName, senderAddress, addressees, attachmentName, null);
        }

        private static string FormatEmailBody(string hsaIdentity, string name, string registerName, string unitName, string templatePathRelative)
        {
            var datetime = DateTime.Now;
            var emailDate = datetime.ToString("yyyy-MM-dd HH:mm");
            var emailTemplate = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(templatePathRelative));
            
            var replacements = new Dictionary<string, string>
            {
                {"{%HSAIdentity%}", hsaIdentity},
                {"{%Name%}", name},
                {"{%RegisterName%}", registerName},
                {"{%UnitName%}", unitName},
                {"{%Date%}", emailDate}
            };

            emailTemplate = replacements.Aggregate(emailTemplate, (current, replacement) => current.Replace(replacement.Key, replacement.Value));

            return emailTemplate;
        }

        public ActionResult LoggGrafikUi(int eventType, int eventNumber, int userId, string eventMessage)
        {
            var logging = new LoggingRepository();
            logging.LoggToDatabase(eventType, eventNumber, userId, eventMessage);

            return null;
        }
    }
}

PharosLoginPortalDK/PharosLoginPortal.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;
using Microsoft.AspNet.Identity;
using PharosLoginPortal.Repository.Database;
using PharosLoginPortal.Repository.Helpers;
using PharosLoginPortal.Repository.Models;
using PharosLoginPortal.Web.Helpers;
using PharosLoginPortal.Web.PharosTokenService;

using System.Security.Principal;
using System.Threading;
using System.IdentityModel.Services;
using System.Security.Claims;
using System.Xml;
using System.Xml.Serialization;
using Newtonsoft.Json;

namespace PharosLoginPortal.Web.Controllers
{

    [Authorize]
    public class UserController : Controller
    {
        [HandleError] 
        public ActionResult Index(bool? logout)
        {
            if (logout.HasValue && logout.Value)
            {
                return RedirectToAction("LogOff", "Login");
            }

            var claimsIdentity = Thread.CurrentPrincipal.Identity as ClaimsIdentity;
            var hsaIdentity = claimsIdentity.Claims.Where(c => c.Type.EndsWith("CvrNumberIdentifier")).Select(cv => cv.Value).First();

            var indexViewModel = new UserIndexViewModel();

            //if (claimsIdentity.IsAuthenticated)
            //{
            //    var userRepository = new UserRepository();
            //    var registerRepository = new RegisterRepository();

            //    foreach (var register in registerRepository.GetAllRegisters())
            //    {
            //        try
            //        {
            //            var logins = userRepository.GetUsersSithsLogins(register.Id, hsaIdentity);
            //            foreach (var login in logins)
            //            {
            //                login.RegisterName = register.RegisterName;
            //                login.LoginUrl = register.RegisterURL;

            //                var loginRequests = userRepository.GetUsersSithsLoginRequests(register.Id, hsaIdentity).ToArray();

            //                foreach (var request in loginRequests)
            //                {
            //                    request.RegisterName = register.RegisterName;
            //                }

            //                indexViewModel.Logins.AddRange(logins);
            //                indexViewModel.LoginRequests.AddRange(loginRequests);
            //            }
            //        }
            //        catch (Exception e)
            //        {
            //            LogHelper.Error(e.Message, e);
            //        }
            //    }
            //}


            //var user = User.GetAuthifyUser();
            //LogHelper.Debug(string.Format("UserController - Index. HSA-Id: {0}", user.hsa_id));
            var registerRepository = new RegisterRepository();
            var userRepository = new UserRepository();
            //var indexViewModel = new UserIndexViewModel();

            foreach (var register in registerRepository.GetAllRegisters())
            {
                try
                {
                    //var hsaIdentity = user.hsa_id;
                    indexViewModel.HsaId = hsaIdentity;
                    var logins = userRepository.GetUsersSithsLogins(register.Id, hsaIdentity).ToArray();

                    foreach (var login in logins)
                    {
                        login.RegisterName = register.RegisterName;
                        login.LoginUrl = register.RegisterURL;

                        // Admins and Trainers get the admin application
                        if (login.RoleId == 2 || login.RoleId == 5)
                        {
                            login.LoginUrl = register.AdminURL;
                        }

                        if (!login.LoginUrl.EndsWith("/"))
                        {
                            login.LoginUrl += "/";
                        }
                    }

                    //Jämför register Id för att sätta namn på request name.
                    var loginRequests = userRepository.GetUsersSithsLoginRequests(register.Id, hsaIdentity).ToArray();

                    foreach (var request in loginRequests)
                    {
                        request.RegisterName = register.RegisterName;
                    }

                    indexViewModel.Logins.AddRange(logins);
                    indexViewModel.LoginRequests.AddRange(loginRequests);
                }
                catch (Exception e)
                {
                    LogHelper.Error(e.Message, e);
                }
            }
            return View(indexViewModel);
        }

        public RedirectResult LoggGrafikUi(int eventType, int eventNumber, string eventMessage, int userId, string url)
        {
            var user = User.GetAuthifyUser();
            var debug = string.Format("SithToken: {0}, uid: {1}, name: {2}, hsa_id: {3}",
                user.SithToken, user.uid, user.name, user.hsa_id);
            LogHelper.Debug(debug);
            
            var logging = new LoggingRepository();
            logging.LoggToDatabase(eventType, eventNumber, userId, eventMessage);
            
            var service = new TokenWebService();
            var tokenServiceUrl = ConfigHelper.GetTokenWebServiceUrl();
            if (!string.IsNullOrEmpty(tokenServiceUrl))
            {
                service.Url = tokenServiceUrl;
            }

            var token = service.RequestToken(User.GetAuthifyUser().hsa_id);

            LogHelper.Debug("Service returned token: " + token);

            var redirectUrl = string.Format("{0}?pharosToken={1}", url, token);
            return Redirect(redirectUrl);
        }

        public string GetToken(int eventType, int eventNumber, string eventMessage, int userId, int loginId, string url, string unitId)
        {
            var user = User.GetAuthifyUser();
            var doc = new XDocument(new XElement("Credentials",
                                           new XElement("SithsId", user.hsa_id),
                                           new XElement("UserId"),
                                           new XElement("Password"),
                                           new XElement("UnitId", unitId),
                                           new XElement("UnitName"),
                                           new XElement("LoginId", loginId.ToString())));

            LogHelper.Debug("XML:\n" + doc);
            
            var service = new TokenWebService();
            var tokenServiceUrl = ConfigHelper.GetTokenWebServiceUrl();
            if (!string.IsNullOrEmpty(tokenServiceUrl))
            {
                service.Url = tokenServiceUrl;
            }

            var token = service.RequestToken(doc.ToString());
            var redirectUrl = string.Format("{0}Account/LoginFromPortal/?pharosToken={1}", url, token);

            var logging = new LoggingRepository();
            logging.LoggToDatabase(eventType, eventNumber, userId, eventMessage);
            LogHelper.Debug(string.Format("Redirecting user {0} to {1}", user.hsa_id, redirectUrl));

            return redirectUrl;
        }
    }
}

PharosLoginPortalDK/PharosLoginPortal.Web/Views/User/Index.cshtml
@model PharosLoginPortal.Repository.Models.UserIndexViewModel

@{
    var authifyUser = User.GetAuthifyUser();
}

<header>
    @Scripts.Render("~/Scripts/Portal/user.js")
</header>


    @*Användaruppgifter*@
    <div style="height:819px; width:20%; float:left; margin-left: 5%; background-color:#EDEDE4; padding:20px;">
        <h4>Velkommen!</h4>
        <h5>Venligst Kontroller, at dine oplysninger er korrekte, før du fortsætter</h5>
        <hr />
        <div class="form-group">
            <label>NemID Identity:</label>
            <input id="hsa_id" name="hsa_id" class="form-control" type="text" value="@authifyUser.hsa_id" readonly />
            <br />
            <br />
            <label>Navn</label>
            <input class="form-control" type="text" value="@authifyUser.name" />
            <br />
            <br />
            <label>Organisation</label>
            <input class="form-control" type="text" value="@authifyUser.organization_name" />
            <br />
            <br />
            <label>E-mail</label>
            <input id="editUserEmail" class="form-control" type="email" value="@authifyUser.email" />

        </div>
        <br/>
        <form action="@Url.Action("LogOff", "Login")">
            <button class="pull-right btn btn-danger" type="submit"><span class="glyphicon glyphicon-log-out"></span> Log ud</button>
        </form>
    </div>

    @*LOGINS_LISTA*@
    <div class="loginList pull-right" style="height:500px;">
    <label>Klikke på registret for at logge ind</label>


    <button class="btn btn-sm btn-primary pull-right" onclick="location.href='@Url.Action("Index", "NewLogin")'"><span class="glyphicon glyphicon-plus" style="border:0;"></span> Tilføj Login</button>
    <br />
    <hr />

    <div style="max-height:350px; overflow:auto;">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Register</th>
                    <th>Enhetens navn</th>
                    <th>Kommune</th>
                    <th>Amt?</th>
                    <th>Rolle</th>
                </tr>
            </thead>


            <tbody>
                @{

                    foreach (var item in Model.Logins)
                    {
                        <tr class="clickableRow" data-url='@item.LoginUrl' data-name='@item.RegisterName' data-userid="@item.UserId" data-loginid="@item.LoginId" data-unitid="@item.UnitId">
                            <td>@item.RegisterName</td>
                            @if(item.RoleId == 2)
                            {
                            <td></td>
                            <td></td>
                            <td></td>
                            }
                            else
                            {
                            <td>@item.UnitName</td>
                            <td>@item.CommunityName</td>
                            <td>@item.CountyName</td>
                            }
                            <td>@item.RoleName</td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>

</div>
      
        

   
 
       

   @*REGISTRERADE FÖRFRÅGNINGAR*@
    <div class="loginList pull-right subbox">
    <label>Skickade förfrågningar</label>
    <hr />
    <div style="max-height:200px; overflow:auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Register</th>
                    <th>Enhetens namn</th>
                    <th>Kommun</th>
                    <th>Län</th>
                    <th>Admins kommentarer</th>
                    <th>Skapad</th>
                </tr>

            </thead>
            <tbody>
                @foreach (var item in Model.LoginRequests)
                {
                    <tr>
                        <td>@item.RegisterName</td>
                        <td>@item.UnitName</td>
                        <td>@item.CommunityName</td>
                        <td>@item.CountyName</td>
                        <td>@item.AdminComment</td>
                        <td>@item.CreateDate.ToString("yyyy-MM-dd")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


 